### ISSUE TITLE
Does ORM support subclass?

### ISSUE THREAD

**Issue by diuming** [Kitura/Swift-Kuery-ORM#127]
I try to use my `subclass` `ClassB ` conforms with `Model`.
Then create database table using `createTableSync()` function.
but only `id` and `value3`'s are created.

how about `value1` and `value2` of `ClassA`?

```
class ClassA: Codable {
    var value1: Int
    var value2: Int
}

final class ClassB: ClassA {
    id: Int
    var value3: Int
}

extension ClassB: Model {
    static let tableName =  "ClassBs"
}
```

**Comment by igorL-Pg** [comment]
Class inheritance works just fine, but you have to rewrite your required init(from decoder: Decoder). This is a bit odd because the Model protocol conforms to Codable protocol and subclass inherits from a class that also conforms to the same protocol. Therefore encoding and decoding for basic data types should be working out fo a box.

**Comment by igorL-Pg** [comment]
You also have to override func encode(to encoder: Encoder) throws in
the case that you want to use save or update function.

**Comment by diuming** [comment]
@igorL-Pg got it.
