### ISSUE TITLE
Renaming the class "Database".

### ISSUE THREAD

**Issue by ghost** [Kitura/Swift-Kuery-ORM#22]
Kitura-CouchDB (https://github.com/IBM-Swift/Kitura-CouchDB) is already using it.
Can we renaming it?

**Comment by EnriqueL8** [comment]
Hey @invencode, an idea would be to create a `typealias` in your code such as:
```[swift]
typealias CouchDatabase = Kitura-CouchDB.Database
```
Could that be fine?

**Comment by invencode** [comment]
@EnriqueL8, It could be fine for new projects.
But, it would be great if there is a way to use Swift-Kuery-ORM with existing projects without any code changes.

**Comment by EnriqueL8** [comment]
@invencode Instead of making changes to your CouchDB code,  you could `typealias` the ORM Database?
```swift
typealias ORMDatabase = Swift-Kuery-ORM.Database
```

**Comment by invencode** [comment]
@EnriqueL8 , The two options you mentioned (either using typealias for CouchDB.Database or SwiftKueryORM.Database) had occurred to me, but even though that kind of fix is possible, I suggested changing the name from “Database” to “ORMDatabase” mainly for three reasons:

1. Using typealias is very simple, but avoiding its use at all seems simpler. Disregarding the convenience of not having to use typealias, however, using typealias does not seem to work 100% of the time. I still get an error, ‘Database’ is ambiguous for type lookup in this context.

2. For many developers who use Kitura and want to use both SwiftKueryORM and CouchDB, I think the two frameworks both having the “Database” class could continually cause issues in the future.

3. Because SwiftKueryORM is in such an early development state, it seems like an ideal time to switch the names and minimize the impact of the naming conflict here.

**Comment by djones6** [comment]
@kilnerm We could consider adding a public typealias to the ORM (and/or Kitura-CouchDB) to provide an alternate name to use where there would otherwise be ambiguity.

**Comment by NathanFallet** [comment]
I've added both aliases, so they can be used (when both PR merged)
